/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TanstackRouteImport } from './routes/tanstack'
import { Route as ReduxRouteImport } from './routes/redux'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProductsRouteRouteImport } from './routes/products/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsMobileRouteImport } from './routes/products/mobile'
import { Route as ProductsLaptopRouteImport } from './routes/products/laptop'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as SuccessPaymentIntentIdOrderIdRouteImport } from './routes/success.$paymentIntentId.$orderId'

const TanstackRoute = TanstackRouteImport.update({
  id: '/tanstack',
  path: '/tanstack',
  getParentRoute: () => rootRouteImport,
} as any)
const ReduxRoute = ReduxRouteImport.update({
  id: '/redux',
  path: '/redux',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsMobileRoute = ProductsMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsLaptopRoute = ProductsLaptopRouteImport.update({
  id: '/laptop',
  path: '/laptop',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessPaymentIntentIdOrderIdRoute =
  SuccessPaymentIntentIdOrderIdRouteImport.update({
    id: '/success/$paymentIntentId/$orderId',
    path: '/success/$paymentIntentId/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/payment': typeof PaymentRoute
  '/redux': typeof ReduxRoute
  '/tanstack': typeof TanstackRoute
  '/auth/login': typeof AuthLoginRoute
  '/products/laptop': typeof ProductsLaptopRoute
  '/products/mobile': typeof ProductsMobileRoute
  '/products/': typeof ProductsIndexRoute
  '/success/$paymentIntentId/$orderId': typeof SuccessPaymentIntentIdOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/payment': typeof PaymentRoute
  '/redux': typeof ReduxRoute
  '/tanstack': typeof TanstackRoute
  '/auth/login': typeof AuthLoginRoute
  '/products/laptop': typeof ProductsLaptopRoute
  '/products/mobile': typeof ProductsMobileRoute
  '/products': typeof ProductsIndexRoute
  '/success/$paymentIntentId/$orderId': typeof SuccessPaymentIntentIdOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products': typeof ProductsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/payment': typeof PaymentRoute
  '/redux': typeof ReduxRoute
  '/tanstack': typeof TanstackRoute
  '/auth/login': typeof AuthLoginRoute
  '/products/laptop': typeof ProductsLaptopRoute
  '/products/mobile': typeof ProductsMobileRoute
  '/products/': typeof ProductsIndexRoute
  '/success/$paymentIntentId/$orderId': typeof SuccessPaymentIntentIdOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/about'
    | '/cart'
    | '/payment'
    | '/redux'
    | '/tanstack'
    | '/auth/login'
    | '/products/laptop'
    | '/products/mobile'
    | '/products/'
    | '/success/$paymentIntentId/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/payment'
    | '/redux'
    | '/tanstack'
    | '/auth/login'
    | '/products/laptop'
    | '/products/mobile'
    | '/products'
    | '/success/$paymentIntentId/$orderId'
  id:
    | '__root__'
    | '/'
    | '/products'
    | '/about'
    | '/cart'
    | '/payment'
    | '/redux'
    | '/tanstack'
    | '/auth/login'
    | '/products/laptop'
    | '/products/mobile'
    | '/products/'
    | '/success/$paymentIntentId/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsRouteRoute: typeof ProductsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  PaymentRoute: typeof PaymentRoute
  ReduxRoute: typeof ReduxRoute
  TanstackRoute: typeof TanstackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  SuccessPaymentIntentIdOrderIdRoute: typeof SuccessPaymentIntentIdOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tanstack': {
      id: '/tanstack'
      path: '/tanstack'
      fullPath: '/tanstack'
      preLoaderRoute: typeof TanstackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redux': {
      id: '/redux'
      path: '/redux'
      fullPath: '/redux'
      preLoaderRoute: typeof ReduxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/mobile': {
      id: '/products/mobile'
      path: '/mobile'
      fullPath: '/products/mobile'
      preLoaderRoute: typeof ProductsMobileRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/laptop': {
      id: '/products/laptop'
      path: '/laptop'
      fullPath: '/products/laptop'
      preLoaderRoute: typeof ProductsLaptopRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success/$paymentIntentId/$orderId': {
      id: '/success/$paymentIntentId/$orderId'
      path: '/success/$paymentIntentId/$orderId'
      fullPath: '/success/$paymentIntentId/$orderId'
      preLoaderRoute: typeof SuccessPaymentIntentIdOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProductsRouteRouteChildren {
  ProductsLaptopRoute: typeof ProductsLaptopRoute
  ProductsMobileRoute: typeof ProductsMobileRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteRouteChildren: ProductsRouteRouteChildren = {
  ProductsLaptopRoute: ProductsLaptopRoute,
  ProductsMobileRoute: ProductsMobileRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteRouteWithChildren = ProductsRouteRoute._addFileChildren(
  ProductsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsRouteRoute: ProductsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  PaymentRoute: PaymentRoute,
  ReduxRoute: ReduxRoute,
  TanstackRoute: TanstackRoute,
  AuthLoginRoute: AuthLoginRoute,
  SuccessPaymentIntentIdOrderIdRoute: SuccessPaymentIntentIdOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
